### ISSUE TITLE
lit-element is dependent on internal Cisco URL

### ISSUE THREAD

**Issue by edumansky** [CiscoDevNet/webex-contact-center-widget-starter#1]
Looks like some of the libraries referenced in package.json point to Cisco internal URLs. Building the code is not possible. When trying yarn in the `lit-element` folder:

$ yarn
yarn install v1.13.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://engci-maven.cisco.com/artifactory/api/npm/agentx-npm/@agentx/agentx-js-api/-/@agentx/agentx-js-api-1.0.9-beta.tgz: getaddrinfo ENOTFOUND engci-maven.cisco.com engci-maven.cisco.com:443".
info If you think this is a bug, please open a bug report with the information provided in "/Users/Ed/Dropbox (Personal)/Dev/webex-contact-center-widget-starter/lit-element/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by yananym** [comment]
Hello Ed! JS-API is not internal, but it does require an auth token to be obtained from your Cisco contact. We are required to publish on internal Cisco artifactory - the package is available externally without VPN but still requires authorization. This is the only drawback.

**Comment by edumansky** [comment]
Got it. As a partner, who would we reach out to for this auth token?

**Comment by yananym** [comment]
Agent Desktop PM Rajiv Krishnan should be able to help
