### ISSUE TITLE
In lit-element starter kit multiple buttons are not working  

### ISSUE THREAD

**Issue by sameyada** [CiscoDevNet/webex-contact-center-widget-starter#24]
Buttons inside Desktop agent contact and action  are not working and throwing error.

**Comment by yananym** [comment]
@sameyada i will add an issue template, but until i do, please follow common sense in describing issues: steps to reproduce, exact error messages, what buttons you are clicking. It is impossible to debug with no information.

**Comment by yananym** [comment]
Closing as invalid after speaking with Shivam
